spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /**
  web:
    resources:
      static-locations: [classpath:/static/]
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cpcmanage?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: org.msy.boot.entity
