spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /**
  web:
    resources:
      static-locations: [classpath:/static/]
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cpcmanage?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #全局启动或金庸延迟加载.当禁用时所有关联对象都会及时加载
    lazy-loading-enabled: true
    #为false时 所有关联对象都会按需求加载
    aggressive-lazy-loading: false
  type-aliases-package: org.msy.boot.entity